name = "Automa"
uuid = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
authors = ["Kenta Sato <bicycle1885@gmail.com>", "Jakob Nybo Nissen <jakobnybonissen@gmail.com"]
version = "1.0.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
julia = "1.6"
PrecompileTools = "1"
TranscodingStreams = "0.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[targets]
test = ["Test", "TranscodingStreams"]
