[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
Automa = "1"
TranscodingStreams = "0.9"
Documenter = "0.24 - 0.26"
